name: Refactor
description: Refactoring Code
labels: ["refactor"]
body:
  - type: textarea
    id: desc
    attributes: { label: Description, placeholder: What code is being refactored and why? }
    validations: { required: true }
